### ISSUE TITLE
学历背景较好，毕业能进大厂算法，还有必要润吗

### ISSUE THREAD

**Issue by yorhaha** [wahyd4/work-in-australia#48]
目前有机会毕业时拿到签证，主要出于以下考虑润：

- WLB
- 35岁以后不被裁
- 一二线城市的房价压力较大

其他方面澳洲比国内差距都挺大，并且没有工作经验可能很难找到 Data 工作，需要转开发。在考虑要不要润。

**Comment by wahyd4** [comment]
成都的房价也还好吧，在新一线城市里面也不算太高，只是国内卷是真的卷，但是国内技术挑战性更大也是真的，初期成长会更快，毕竟国内很多公司的用户数，需要处理的数据流量都比澳洲大得多。
其次，你是人在澳洲读书吗？澳洲Data 也有招毕业生的啊，只是今年感觉经济大环境不好，职位没有以前多。
如果你纠结，并且你毕业就能拿到签证的话，可以先拿到PR，到时候不喜欢澳洲可以再回国工作几年看看，这样多一条退路。

**Comment by yorhaha** [comment]
感谢解答！

目前国内读硕，需要蹭陪读签或者配偶签😂

毕业没有工作经验的话，加上英语听说能力一般，即使有签证也很难面到 offer 吧，或者拿比较低的薪水（相比国内大厂算法）。

最近看了不少信息，如果按照澳元购买力是人民币 2.5 倍来计算，好像除了房贷压力会小之外（而且不能在房价高的城市），生活的其他方面并不会得到明显改善，甚至会下降。所以，个人感觉润到澳洲是一种牺牲现在投资未来的选择。（主要还是舍不得这段感情😵

您说的先拿到 PR 作为退路的建议确实很好，感谢！
